fix exa driver version
keboola/php-db-import-export pull request #107
Opened 2022-05-23 09:05 UTC by fejjo

2022-05-23 09:55 UTC, fejjo commented
@jirkasemmler prosim ta trochu nechapem ti zadanie,  KBC-2617 ma sa sem pridavat spustanie testov pre exasol? Napr ani synapse testy tu nebezia ked dam PR
<img width="870" alt="Screenshot 2022-05-23 at 11 55 02" src="https://user-images.githubusercontent.com/6448364/169794203-905baa39-3acc-4f1b-998a-8246533ea3a4.png">

2022-05-31 17:22 UTC, zajca requested changes
Enom drobnost, jinak je to řekl bych cajk

2022-05-31 17:22 UTC, zajca commented on .github/workflows/tests.yml
> +    needs: load-abs
Exasol potřebuje s3 assety

2022-06-01 06:38 UTC, fejjo commented on .github/workflows/tests.yml
> +    needs: load-abs
Dik upravil som 👍

2022-06-01 06:58 UTC, merged