Fix bug check destination column type
keboola/php-db-import-export pull request #89
Opened 2021-12-10 15:40 UTC by zajca

2021-12-14 14:46 UTC, zajca commented
Spadnul Synapse test v jiné suitě, která tento kód nepoužívá. Exasol suitu sem vypnul protože cloud.exasol sa chová poslední dobů uplně nepředvídatelně a API vrací :hankey:

2021-12-15 08:56 UTC, jirkasemmler requested changes
:+1: za ty commity, hezky se v tom orientuje!

fix je asi v pohode a je na to test, ale kdyz uz takto testujeme numeric, tak bych asi byl klidnejsi, kdybychom do toho testu integrovali i par dalsich typu, aspon od kazdeho basetypu jednoho zastupce. Prakticky by tomu testu stacilo rozsirit sloupce a kazdemu dat jinej typ. 

Proste abychom to overili nejen na NUMERIC, ale obecne na vsechny datove typy a nevyskocil na nas podobny problem s BOOLEANem jen kvuli tomu, ze jsme otestovali jen NUMERIC

2021-12-15 12:29 UTC, zajca commented
> +1 za ty commity, hezky se v tom orientuje!
> 
> fix je asi v pohode a je na to test, ale kdyz uz takto testujeme numeric, tak bych asi byl klidnejsi, kdybychom do toho testu integrovali i par dalsich typu, aspon od kazdeho basetypu jednoho zastupce. Prakticky by tomu testu stacilo rozsirit sloupce a kazdemu dat jinej typ.
> 
> Proste abychom to overili nejen na NUMERIC, ale obecne na vsechny datove typy a nevyskocil na nas podobny problem s BOOLEANem jen kvuli tomu, ze jsme otestovali jen NUMERIC

Vůbec z tebe nemám radost, ale přidal sem to tam.

2021-12-15 14:45 UTC, jirkasemmler approved these changes
:+1:

2021-12-15 19:38 UTC, merged